# -*- coding: utf-8 -*-
"""Predicting customer churn using machine learning to  uncover hidden patterns.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/169qTGZmLexsUC_h0shuLasHT3lb61JeP
"""

# -*- coding: utf-8 -*-
"""Predicting customer churn using machine learning to  uncover hidden patterns .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HIFxj-cJVE1dUcdXi2mGhduiRgIQ3Fku
"""

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, confusion_matrix

# Load data
# If the file is in the same directory as the script, this should work:

# If not, replace with the correct file path
# df = pd.read_csv("/path/to/your/file/customer_churn.csv")

# ... (rest of your code remains the same) ...